name: feed
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.2.3
  http: ^1.4.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  page_transition: ^2.2.1
  flutter_secure_storage: ^9.2.4
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  another_flushbar: ^1.12.30
  flutter_bloc: ^9.1.1
  characters: ^1.4.0

dev_dependencies:
  flutter_test: 
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/images/lefthand.png
    - assets/images/moon.png
    - assets/images/sun.png
    - assets/images/righthand.png
    - assets/images/login.png 
    - assets/images/signup.png
    - assets/images/googlelight.png
    - assets/images/—Pngtree—girl social media advertising_6477605.png
    - assets/images/—Pngtree—hand drawn pink girl social_5322751.png
    - assets/images/vecteezy_mobile-phone-with-love-for-social-media_12414995.png
    - assets/images/pngwing.com.png
    - assets/images/v916-nunny-532-removebg-preview.png

  fonts:
    - family: "Primary"
      fonts:
        - asset: assets/fonts/CrimsonPro-VariableFont_wght.ttf
    - family: "Secondary"
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
    - family: "Texxt"
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
    - family: "special"
      fonts:
        - asset: assets/fonts/UnifrakturMaguntia-Regular.ttf
